"""initial schema

Revision ID: 724c990b797a
Revises: 
Create Date: 2026-08-15 18:48:47.206885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724c990b797a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('cloth_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_stitching_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_fabric_metres', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reference_body_cm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ai_prompt_noun', sa.String(length=200), nullable=False),
    sa.Column('production_days', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_cloth_types_id'), 'cloth_types', ['id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cost_per_metre', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_metres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('swatch_css', sa.String(length=200), nullable=True),
    sa.Column('ai_prompt_term', sa.String(length=200), nullable=False),
    sa.Column('care_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('design_option_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloth_type_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('selection_type', sa.String(length=10), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cloth_type_id'], ['cloth_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloth_type_id', 'code')
    )
    op.create_index(op.f('ix_design_option_groups_id'), 'design_option_groups', ['id'], unique=False)
    op.create_table('material_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=False),
    sa.Column('ai_prompt_term', sa.String(length=120), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'name')
    )
    op.create_index(op.f('ix_material_colors_id'), 'material_colors', ['id'], unique=False)
    op.create_table('measurement_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cloth_type_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('letter', sa.String(length=2), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('affects_fabric', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cloth_type_id'], ['cloth_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloth_type_id', 'field_key')
    )
    op.create_index(op.f('ix_measurement_fields_id'), 'measurement_fields', ['id'], unique=False)
    op.create_table('saved_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cloth_type_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('estimated_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mockup_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cloth_type_id'], ['cloth_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_designs_id'), 'saved_designs', ['id'], unique=False)
    op.create_table('user_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bust', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hip', sa.Float(), nullable=True),
    sa.Column('shoulder', sa.Float(), nullable=True),
    sa.Column('sleeve', sa.Float(), nullable=True),
    sa.Column('total_length', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('inseam', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_measurements_id'), 'user_measurements', ['id'], unique=False)
    op.create_table('design_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('ai_prompt_term', sa.String(length=200), nullable=False),
    sa.Column('stitching_premium', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fabric_multiplier', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['design_option_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'code')
    )
    op.create_index(op.f('ix_design_options_id'), 'design_options', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=True),
    sa.Column('cloth_type_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_color_id', sa.Integer(), nullable=True),
    sa.Column('cloth_type_name', sa.String(length=100), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('color_name', sa.String(length=60), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('design_options_snapshot', sa.JSON(), nullable=False),
    sa.Column('measurements_snapshot', sa.JSON(), nullable=False),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('fabric_metres_used', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('price_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_stitching', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_material', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_delivery', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_breakdown', sa.JSON(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mockup_url', sa.String(length=500), nullable=True),
    sa.Column('mockup_prompt', sa.Text(), nullable=True),
    sa.Column('mockup_model', sa.String(length=120), nullable=True),
    sa.Column('mockup_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cloth_type_id'], ['cloth_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_color_id'], ['material_colors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('mockup_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=150), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mockup_generations_id'), 'mockup_generations', ['id'], unique=False)
    op.create_table('order_reference_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_reference_images_draft_id'), 'order_reference_images', ['draft_id'], unique=False)
    op.create_index(op.f('ix_order_reference_images_id'), 'order_reference_images', ['id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_reference_images_id'), table_name='order_reference_images')
    op.drop_index(op.f('ix_order_reference_images_draft_id'), table_name='order_reference_images')
    op.drop_table('order_reference_images')
    op.drop_index(op.f('ix_mockup_generations_id'), table_name='mockup_generations')
    op.drop_table('mockup_generations')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_design_options_id'), table_name='design_options')
    op.drop_table('design_options')
    op.drop_index(op.f('ix_user_measurements_id'), table_name='user_measurements')
    op.drop_table('user_measurements')
    op.drop_index(op.f('ix_saved_designs_id'), table_name='saved_designs')
    op.drop_table('saved_designs')
    op.drop_index(op.f('ix_measurement_fields_id'), table_name='measurement_fields')
    op.drop_table('measurement_fields')
    op.drop_index(op.f('ix_material_colors_id'), table_name='material_colors')
    op.drop_table('material_colors')
    op.drop_index(op.f('ix_design_option_groups_id'), table_name='design_option_groups')
    op.drop_table('design_option_groups')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_cloth_types_id'), table_name='cloth_types')
    op.drop_table('cloth_types')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
